#!/usr/bin/env bash
set -euo pipefail

SAMPLES_TSV=""
MAX_RSS_KB="${MAX_RSS_KB:-0}"
MAX_NATIVE_PENDING="${MAX_NATIVE_PENDING:-0}"
MAX_PANIC_LINES="${MAX_PANIC_LINES:-0}"
MAX_EXTERNAL_CORE_ERRORS="${MAX_EXTERNAL_CORE_ERRORS:-0}"
MAX_CPU_PERCENT="${MAX_CPU_PERCENT:-0}"
MAX_RSS_GROWTH_KB="${MAX_RSS_GROWTH_KB:-0}"
MIN_NATIVE_USER_DELTAS="${MIN_NATIVE_USER_DELTAS:-0}"

usage() {
  cat <<'USAGE'
Usage: native_resource_gate.sh --samples samples.tsv [limits]

Validates TSV files generated by scripts/ops/native_resource_watch.sh.

Limits:
  --max-rss-kb N
  --max-rss-growth-kb N
  --max-native-pending N
  --max-panic-lines N
  --max-external-core-errors N
  --max-cpu-percent N
  --min-native-user-deltas N
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --samples)
      SAMPLES_TSV="$2"
      shift 2
      ;;
    --max-rss-kb)
      MAX_RSS_KB="$2"
      shift 2
      ;;
    --max-rss-growth-kb)
      MAX_RSS_GROWTH_KB="$2"
      shift 2
      ;;
    --max-native-pending)
      MAX_NATIVE_PENDING="$2"
      shift 2
      ;;
    --max-panic-lines)
      MAX_PANIC_LINES="$2"
      shift 2
      ;;
    --max-external-core-errors)
      MAX_EXTERNAL_CORE_ERRORS="$2"
      shift 2
      ;;
    --max-cpu-percent)
      MAX_CPU_PERCENT="$2"
      shift 2
      ;;
    --min-native-user-deltas)
      MIN_NATIVE_USER_DELTAS="$2"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [ -z "${SAMPLES_TSV}" ] || [ ! -s "${SAMPLES_TSV}" ]; then
  echo "--samples must point to a non-empty TSV file" >&2
  exit 2
fi

awk -v max_rss="${MAX_RSS_KB}" \
  -v max_growth="${MAX_RSS_GROWTH_KB}" \
  -v max_pending="${MAX_NATIVE_PENDING}" \
  -v max_panic="${MAX_PANIC_LINES}" \
  -v max_external="${MAX_EXTERNAL_CORE_ERRORS}" \
  -v max_cpu="${MAX_CPU_PERCENT}" \
  -v min_deltas="${MIN_NATIVE_USER_DELTAS}" '
BEGIN {
  FS = "\t"
  failed = 0
  rows = 0
  first_rss = -1
  last_rss = 0
  max_seen_rss = 0
  max_seen_cpu = 0
  max_seen_pending = 0
  max_seen_panic = 0
  max_seen_external = 0
  max_seen_deltas = 0
}
NR == 1 {
  for (i = 1; i <= NF; i++) {
    idx[$i] = i
  }
  required = "active_state sub_state rss_kb cpu_percent native_pending external_core_errors panic_lines native_user_deltas"
  split(required, names, " ")
  for (i in names) {
    if (!(names[i] in idx)) {
      print "missing column: " names[i] > "/dev/stderr"
      exit 2
    }
  }
  next
}
{
  rows++
  active = $idx["active_state"]
  sub_state = $idx["sub_state"]
  rss = $idx["rss_kb"] + 0
  cpu = $idx["cpu_percent"] + 0
  pending = $idx["native_pending"]
  external = $idx["external_core_errors"] + 0
  panic = $idx["panic_lines"] + 0
  deltas = $idx["native_user_deltas"] + 0

  if (pending == "-" || pending == "") {
    pending = 0
  }
  pending += 0

  if (active != "active" || sub_state != "running") {
    print "service not running at row " NR ": " active "/" sub_state > "/dev/stderr"
    failed = 1
  }
  if (first_rss < 0) {
    first_rss = rss
  }
  last_rss = rss
  if (rss > max_seen_rss) {
    max_seen_rss = rss
  }
  if (cpu > max_seen_cpu) {
    max_seen_cpu = cpu
  }
  if (pending > max_seen_pending) {
    max_seen_pending = pending
  }
  if (panic > max_seen_panic) {
    max_seen_panic = panic
  }
  if (external > max_seen_external) {
    max_seen_external = external
  }
  if (deltas > max_seen_deltas) {
    max_seen_deltas = deltas
  }

  if (max_rss > 0 && rss > max_rss) {
    print "rss_kb exceeded: row=" NR " rss=" rss " limit=" max_rss > "/dev/stderr"
    failed = 1
  }
  if (max_pending >= 0 && pending > max_pending) {
    print "native_pending exceeded: row=" NR " native_pending=" pending " limit=" max_pending > "/dev/stderr"
    failed = 1
  }
  if (max_panic >= 0 && panic > max_panic) {
    print "panic_lines exceeded: row=" NR " panic_lines=" panic " limit=" max_panic > "/dev/stderr"
    failed = 1
  }
  if (max_external >= 0 && external > max_external) {
    print "external_core_errors exceeded: row=" NR " external_core_errors=" external " limit=" max_external > "/dev/stderr"
    failed = 1
  }
  if (max_cpu > 0 && cpu > max_cpu) {
    print "cpu_percent exceeded: row=" NR " cpu=" cpu " limit=" max_cpu > "/dev/stderr"
    failed = 1
  }
}
END {
  if (rows == 0) {
    print "no sample rows" > "/dev/stderr"
    exit 2
  }
  growth = last_rss - first_rss
  if (max_growth > 0 && growth > max_growth) {
    print "rss growth exceeded: growth_kb=" growth " limit=" max_growth > "/dev/stderr"
    failed = 1
  }
  if (min_deltas > 0 && max_seen_deltas < min_deltas) {
    print "native user deltas below minimum: seen=" max_seen_deltas " min=" min_deltas > "/dev/stderr"
    failed = 1
  }
  print "resource_gate rows=" rows \
    " max_rss_kb=" max_seen_rss \
    " rss_growth_kb=" growth \
    " max_cpu_percent=" max_seen_cpu \
    " max_native_pending=" max_seen_pending \
    " max_panic_lines=" max_seen_panic \
    " max_external_core_errors=" max_seen_external \
    " max_native_user_deltas=" max_seen_deltas
  exit failed
}' "${SAMPLES_TSV}"
